name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11.5
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'

      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Allure
        run: |
          ALLURE_VERSION=2.23.0
          ALLURE_DIR="/home/runner/.allure"
          mkdir -p "$ALLURE_DIR"
          wget "https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/${ALLURE_VERSION}/allure-commandline-${ALLURE_VERSION}.tgz"
          tar -zxvf "allure-commandline-${ALLURE_VERSION}.tgz" -C "$ALLURE_DIR" --strip-components=1
          echo "$ALLURE_DIR/bin" >> $GITHUB_PATH

      - name: Run tests
        run: |
          cd tests
          pytest --alluredir=allure-results

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean

      - name: Deploy Allure report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report

      - name: Get Allure report URL
        run: |
          allure_host_url="https://${{ github.actor }}.github.io/${{ github.repository }}"
          allure_url="${allure_host_url}/${GITHUB_REF##*/}"
          echo "Allure Report URL: ${allure_url}"